//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DSIGE_InspeccionesEntities : DbContext
    {
        public DSIGE_InspeccionesEntities()
            : base("name=DSIGE_InspeccionesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LogsNEW_LIST_INSPECCION_CAB_WEB_II> LogsNEW_LIST_INSPECCION_CAB_WEB_II { get; set; }
        public virtual DbSet<Megas> Megas { get; set; }
        public virtual DbSet<Prueba> Prueba { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_AccesoOpciones> tbl_AccesoOpciones { get; set; }
        public virtual DbSet<tbl_Actividad> tbl_Actividad { get; set; }
        public virtual DbSet<tbl_Anomalia> tbl_Anomalia { get; set; }
        public virtual DbSet<tbl_Anomalia_TipoInspeccion> tbl_Anomalia_TipoInspeccion { get; set; }
        public virtual DbSet<tbl_Areas> tbl_Areas { get; set; }
        public virtual DbSet<tbl_Caracteristica_Vehiculo> tbl_Caracteristica_Vehiculo { get; set; }
        public virtual DbSet<tbl_Cargo_Personal> tbl_Cargo_Personal { get; set; }
        public virtual DbSet<tbl_Cliente> tbl_Cliente { get; set; }
        public virtual DbSet<tbl_Definicion_Opciones> tbl_Definicion_Opciones { get; set; }
        public virtual DbSet<tbl_Delegacion> tbl_Delegacion { get; set; }
        public virtual DbSet<tbl_EmpresaColaboradora> tbl_EmpresaColaboradora { get; set; }
        public virtual DbSet<tbl_Empresas> tbl_Empresas { get; set; }
        public virtual DbSet<tbl_Estados> tbl_Estados { get; set; }
        public virtual DbSet<tbl_FormatoInspeccion> tbl_FormatoInspeccion { get; set; }
        public virtual DbSet<tbl_grupo> tbl_grupo { get; set; }
        public virtual DbSet<tbl_grupo_dominio> tbl_grupo_dominio { get; set; }
        public virtual DbSet<tbl_Inspeccion_Cab> tbl_Inspeccion_Cab { get; set; }
        public virtual DbSet<tbl_Inspeccion_Cab_Detalle_Foto> tbl_Inspeccion_Cab_Detalle_Foto { get; set; }
        public virtual DbSet<tbl_Inspeccion_Cab_Detalle_SubAnomalia> tbl_Inspeccion_Cab_Detalle_SubAnomalia { get; set; }
        public virtual DbSet<tbl_NivelInspeccion> tbl_NivelInspeccion { get; set; }
        public virtual DbSet<tbl_OT> tbl_OT { get; set; }
        public virtual DbSet<tbl_pais> tbl_pais { get; set; }
        public virtual DbSet<tbl_Perfil> tbl_Perfil { get; set; }
        public virtual DbSet<tbl_perfil_accesos> tbl_perfil_accesos { get; set; }
        public virtual DbSet<tbl_Personal> tbl_Personal { get; set; }
        public virtual DbSet<Tbl_Personal_Cargo> Tbl_Personal_Cargo { get; set; }
        public virtual DbSet<tbl_Personal_Delegacion> tbl_Personal_Delegacion { get; set; }
        public virtual DbSet<tbl_Proyecto> tbl_Proyecto { get; set; }
        public virtual DbSet<tbl_Proyecto_EmpresaColaboradora> tbl_Proyecto_EmpresaColaboradora { get; set; }
        public virtual DbSet<tbl_Tipo_Inspeccion> tbl_Tipo_Inspeccion { get; set; }
        public virtual DbSet<tbl_Tipo_Sancion> tbl_Tipo_Sancion { get; set; }
        public virtual DbSet<tbl_usuarios> tbl_usuarios { get; set; }
        public virtual DbSet<tbl_usuarios_configuracion> tbl_usuarios_configuracion { get; set; }
        public virtual DbSet<tbl_usuarios_configuracion2> tbl_usuarios_configuracion2 { get; set; }
        public virtual DbSet<tbl_Valor_Inspeccion> tbl_Valor_Inspeccion { get; set; }
        public virtual DbSet<Versiones> Versiones { get; set; }
        public virtual DbSet<Logstbl_Inspeccion_Cab> Logstbl_Inspeccion_Cab { get; set; }
        public virtual DbSet<Logstbl_Inspeccion_Cab_Detalle_Foto> Logstbl_Inspeccion_Cab_Detalle_Foto { get; set; }
        public virtual DbSet<Logstbl_tbl_Inspeccion_Cab_Detalle> Logstbl_tbl_Inspeccion_Cab_Detalle { get; set; }
        public virtual DbSet<T_DATA_IMPORTADO_NEW> T_DATA_IMPORTADO_NEW { get; set; }
        public virtual DbSet<T_USUARIO_BORRADO> T_USUARIO_BORRADO { get; set; }
        public virtual DbSet<tbl_AccesoOpciones_1> tbl_AccesoOpciones_1 { get; set; }
        public virtual DbSet<tbl_anomalia_4> tbl_anomalia_4 { get; set; }
        public virtual DbSet<tbl_Anomalia_Back> tbl_Anomalia_Back { get; set; }
        public virtual DbSet<tbl_Anomalia_SMS> tbl_Anomalia_SMS { get; set; }
        public virtual DbSet<tbl_devolucion_campo> tbl_devolucion_campo { get; set; }
        public virtual DbSet<Tbl_Frecuencia> Tbl_Frecuencia { get; set; }
        public virtual DbSet<Tbl_Reporte_Cobra> Tbl_Reporte_Cobra { get; set; }
        public virtual DbSet<tbl_Tipo_Documento> tbl_Tipo_Documento { get; set; }
        public virtual DbSet<tbl_usuarios_Registrados> tbl_usuarios_Registrados { get; set; }
        public virtual DbSet<Temp_Frecuencia> Temp_Frecuencia { get; set; }
        public virtual DbSet<tempo_ec> tempo_ec { get; set; }
        public virtual DbSet<TEMPORAL_Cargo> TEMPORAL_Cargo { get; set; }
        public virtual DbSet<TEMPORAL_Cargo_Personal> TEMPORAL_Cargo_Personal { get; set; }
        public virtual DbSet<testinspeccions> testinspeccions { get; set; }
        public virtual DbSet<Tmp_Inspeccion_Total> Tmp_Inspeccion_Total { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<tbl_Inspeccion_Cab_Detalle> tbl_Inspeccion_Cab_Detalle { get; set; }
    }
}
