//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogsNEW_LIST_INSPECCION_CAB_WEB_II
    {
        public int IdRegistro { get; set; }
        public Nullable<int> id_personal { get; set; }
        public Nullable<int> id_pais { get; set; }
        public Nullable<int> id_grupo { get; set; }
        public string idDelegacion { get; set; }
        public string idInspector { get; set; }
        public string idRespCorreccion { get; set; }
        public Nullable<int> opcion { get; set; }
        public string fecha_Ini { get; set; }
        public string fecha_fin { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
    }
}
