//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logstbl_tbl_Inspeccion_Cab_Detalle
    {
        public int IdRegistro { get; set; }
        public Nullable<int> id_inspeccion_detalle { get; set; }
        public Nullable<int> id_inspeccion { get; set; }
        public Nullable<int> id_personal { get; set; }
        public Nullable<int> id_anomalia { get; set; }
        public string descripcion { get; set; }
        public string valor { get; set; }
        public string levantamiento { get; set; }
        public string foto_levantamiento { get; set; }
        public string descripcion_levantamiento { get; set; }
        public string accionPropuesta_Correctiva { get; set; }
        public string fechaPropuesta_Correctiva { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public string fecha_creacion { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
    }
}
