//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logstbl_Inspeccion_Cab_Detalle_Foto
    {
        public int IdRegistro { get; set; }
        public Nullable<int> id_inspeccion_detalle { get; set; }
        public string nombre_foto { get; set; }
        public string fecha_creacion { get; set; }
    }
}
