//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DATA_IMPORTADO_NEW
    {
        public int id_pais { get; set; }
        public string Nombre_Pais { get; set; }
        public int id_grupo { get; set; }
        public string Nombre_Grupo { get; set; }
        public int id_Empresas { get; set; }
        public string RUC_Empresa { get; set; }
        public string Nombre_Empresa { get; set; }
        public int id_Delegacion { get; set; }
        public string Delegacion { get; set; }
        public int id_EmpresaColaboradora { get; set; }
        public string RUC_Empresa_Colaboradora { get; set; }
        public string Nombre_Empresa_Colaboradora { get; set; }
        public string Tipo_documento { get; set; }
        public string Nro_Documento { get; set; }
        public string Apellidos { get; set; }
        public string Nombres { get; set; }
        public int id_Cargo { get; set; }
        public string Cargo { get; set; }
        public string Estado { get; set; }
        public string Email { get; set; }
        public string Usuario { get; set; }
        public string Contrasenia { get; set; }
        public Nullable<int> id_perfil { get; set; }
        public string Perfil { get; set; }
        public int usuarioxx { get; set; }
    }
}
