//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Perfil
    {
        public tbl_Perfil()
        {
            this.tbl_usuarios = new HashSet<tbl_usuarios>();
            this.tbl_perfil_accesos = new HashSet<tbl_perfil_accesos>();
        }
    
        public int id_perfil { get; set; }
        public string des_perfil { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    
        public virtual ICollection<tbl_usuarios> tbl_usuarios { get; set; }
        public virtual ICollection<tbl_perfil_accesos> tbl_perfil_accesos { get; set; }
    }
}
