//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Personal_Delegacion
    {
        public int id_personal_Delegacion { get; set; }
        public Nullable<int> id_Personal { get; set; }
        public Nullable<int> id_Delegacion { get; set; }
    }
}
