//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Definicion_Opciones
    {
        public tbl_Definicion_Opciones()
        {
            this.tbl_AccesoOpciones = new HashSet<tbl_AccesoOpciones>();
            this.tbl_perfil_accesos = new HashSet<tbl_perfil_accesos>();
        }
    
        public int id_opcion { get; set; }
        public string nombre_opcion { get; set; }
        public string url_opcion { get; set; }
        public Nullable<int> parentID { get; set; }
        public string nombreParentID { get; set; }
        public string urlImagen_Opcion { get; set; }
        public Nullable<int> orden_Opcion { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public string fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public string fecha_edicion { get; set; }
    
        public virtual ICollection<tbl_AccesoOpciones> tbl_AccesoOpciones { get; set; }
        public virtual ICollection<tbl_perfil_accesos> tbl_perfil_accesos { get; set; }
    }
}
