//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Anomalia_TipoInspeccion
    {
        public int id_SubAnomalia { get; set; }
        public int id_TipoInspeccion { get; set; }
        public int id_Anomalia { get; set; }
        public string Codigo_SubAnomalia { get; set; }
        public string Nombre_SubAnomalia { get; set; }
        public int esSubTitulo_SubAnomalia { get; set; }
        public int Orden_SubAnomalia { get; set; }
        public string Grupo_SubAnomalia { get; set; }
        public int Critica_SubAnomalia { get; set; }
        public int estado { get; set; }
        public int usuario_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int usuario_edicion { get; set; }
        public System.DateTime fecha_edicion { get; set; }
    }
}
