//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Anomalia_SMS
    {
        public int id_anomalia_sms { get; set; }
        public Nullable<int> id_pais { get; set; }
        public Nullable<int> id_grupo { get; set; }
        public Nullable<int> id_delegacion { get; set; }
        public Nullable<int> id_ot { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_personal { get; set; }
        public Nullable<int> numero_celular { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    }
}
