//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_usuarios
    {
        public tbl_usuarios()
        {
            this.tbl_AccesoOpciones = new HashSet<tbl_AccesoOpciones>();
            this.tbl_usuarios_configuracion = new HashSet<tbl_usuarios_configuracion>();
        }
    
        public int id_usuario { get; set; }
        public string nro_documento { get; set; }
        public string datos_personales { get; set; }
        public string correo_electronico { get; set; }
        public string usuario_login { get; set; }
        public string contrasenia_login { get; set; }
        public Nullable<int> id_perfil { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public string imei { get; set; }
        public string version { get; set; }
        public Nullable<System.DateTime> fechaInicioSesion { get; set; }
        public Nullable<int> id_Personal { get; set; }
        public string observacion { get; set; }
    
        public virtual ICollection<tbl_AccesoOpciones> tbl_AccesoOpciones { get; set; }
        public virtual tbl_Perfil tbl_Perfil { get; set; }
        public virtual ICollection<tbl_usuarios_configuracion> tbl_usuarios_configuracion { get; set; }
    }
}
