//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Frecuencia
    {
        public int id_frecuencia { get; set; }
        public decimal frecuencia_Ini { get; set; }
        public decimal frecuencia_Fin { get; set; }
        public decimal frecuencia_Valor { get; set; }
    }
}
