//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_perfil_accesos
    {
        public int id_Perfil_Acceso { get; set; }
        public Nullable<int> id_perfil { get; set; }
        public Nullable<int> id_opcion { get; set; }
        public string permisos_opciones { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public string fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public string fecha_edicion { get; set; }
    
        public virtual tbl_Definicion_Opciones tbl_Definicion_Opciones { get; set; }
        public virtual tbl_Perfil tbl_Perfil { get; set; }
    }
}
