//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Anomalia
    {
        public int id_Anomalia { get; set; }
        public Nullable<int> id_formato { get; set; }
        public string codigo_Anomalia { get; set; }
        public string descripcion_Anomalia { get; set; }
        public string anomalia_Critica { get; set; }
        public string anomalia_Critica_General { get; set; }
        public Nullable<int> anomalia_titulo { get; set; }
        public Nullable<int> anomalia_orden { get; set; }
        public string id_ValorInspeccion { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public Nullable<decimal> anomalia_Valor { get; set; }
        public Nullable<int> anomalia_Grupo { get; set; }
        public Nullable<int> id_Empresa { get; set; }
        public string ver_Validacion { get; set; }
        public string Descripcion_Anomalia_Espana { get; set; }
        public Nullable<int> id_grupo { get; set; }
        public Nullable<int> flag_personal_nuevo { get; set; }
    }
}
