//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Inspeccion_Cab_Detalle
    {
        public tbl_Inspeccion_Cab_Detalle()
        {
            this.tbl_Inspeccion_Cab_Detalle_Foto = new HashSet<tbl_Inspeccion_Cab_Detalle_Foto>();
        }
    
        public int id_inspeccion_detalle { get; set; }
        public Nullable<int> id_inspeccion { get; set; }
        public Nullable<int> id_personal { get; set; }
        public Nullable<int> id_anomalia { get; set; }
        public string descripcion { get; set; }
        public string levantamiento { get; set; }
        public string foto_levantamiento { get; set; }
        public string descripcion_levantamiento { get; set; }
        public string id_ValorInspeccion { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public string accionPropuesta_Correctiva { get; set; }
        public Nullable<System.DateTime> fechaPropuesta_Correctiva { get; set; }
        public string Resultado_Inspeccion { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public Nullable<int> id_cargo_personal { get; set; }
        public string disponividad_uso { get; set; }
        public Nullable<int> size { get; set; }
        public Nullable<int> id_tipoInspeccion { get; set; }
        public Nullable<int> personal_sancion { get; set; }
        public Nullable<int> anomalia_critica { get; set; }
        public Nullable<int> id_detalle_anomalia { get; set; }
        public Nullable<System.DateTime> Fecha_Cierre_Correccion { get; set; }
    
        public virtual tbl_Inspeccion_Cab tbl_Inspeccion_Cab { get; set; }
        public virtual ICollection<tbl_Inspeccion_Cab_Detalle_Foto> tbl_Inspeccion_Cab_Detalle_Foto { get; set; }
    }
}
