//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Caracteristica_Vehiculo
    {
        public int id_Caracteristica { get; set; }
        public Nullable<int> id_Empresa { get; set; }
        public Nullable<int> id_formato { get; set; }
        public Nullable<int> titulo_Caracteristica { get; set; }
        public string codigo_Caracteristica { get; set; }
        public string descripcion_Caracteristica { get; set; }
        public Nullable<int> orden_Caracteristica { get; set; }
        public Nullable<int> aplica_Fecha_Caracteristica { get; set; }
        public Nullable<int> aplica_Obs__Caracteristica { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    }
}
