//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NivelInspeccion
    {
        public int id_NivelInspeccion { get; set; }
        public string descripcion_NivelInspeccion { get; set; }
        public Nullable<int> cantidadDias_NivelInspeccion { get; set; }
        public string ColorFondo_NivelInspeccion { get; set; }
        public string ColorFuente_NivelInspeccion { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public Nullable<int> diasEmail_NivelInspecccion { get; set; }
    }
}
