//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_usuarios_configuracion
    {
        public int id_usuario_configuracion { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_pais { get; set; }
        public Nullable<int> id_grupo { get; set; }
        public Nullable<int> id_Empresas { get; set; }
        public Nullable<int> id_Delegacion { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public Nullable<int> id_Proyecto { get; set; }
        public Nullable<int> id_OT { get; set; }
    
        public virtual tbl_Delegacion tbl_Delegacion { get; set; }
        public virtual tbl_grupo tbl_grupo { get; set; }
        public virtual tbl_pais tbl_pais { get; set; }
        public virtual tbl_usuarios tbl_usuarios { get; set; }
    }
}
