//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class testinspeccions
    {
        public long IdRegistro { get; set; }
        public Nullable<long> id_Inspeccion { get; set; }
        public Nullable<int> id_Pais { get; set; }
        public Nullable<int> id_Delegacion { get; set; }
        public Nullable<int> id_Proyecto { get; set; }
        public Nullable<System.DateTime> fecha_Inspeccion { get; set; }
        public Nullable<int> id_Actividad { get; set; }
        public Nullable<int> id_Personal_Inspector { get; set; }
        public Nullable<int> id_Personal_JefeObra { get; set; }
        public Nullable<int> id_TipoInspeccion { get; set; }
        public string Resultado_Inspeccion { get; set; }
        public Nullable<int> id_EmpresaColaboradora { get; set; }
        public Nullable<int> id_Area { get; set; }
        public Nullable<int> id_Personal_Coordinador { get; set; }
        public Nullable<int> id_NivelInspeccion { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> id_Cliente { get; set; }
        public Nullable<int> conjuntas { get; set; }
        public Nullable<int> id_grupo { get; set; }
        public Nullable<long> Id_Inspeccion_Detalle { get; set; }
        public Nullable<int> Id_Personal { get; set; }
        public Nullable<int> Id_Anomalia { get; set; }
        public string Pais { get; set; }
        public string Grupo { get; set; }
        public string CodDelegacion { get; set; }
        public string Delegacion { get; set; }
        public string Proyecto { get; set; }
        public string Autor { get; set; }
        public string JefeObra { get; set; }
        public string TipoInspeccion { get; set; }
        public string EmpresaColaboradora { get; set; }
        public string Area { get; set; }
        public string Coordinador { get; set; }
        public string NivelInspeccion { get; set; }
        public string Cliente { get; set; }
        public Nullable<int> IdFechaInspeccion { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public string Personal { get; set; }
        public string ResultadoDetalle { get; set; }
        public string Descripcion { get; set; }
        public string Resultado { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Row { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> Correcto { get; set; }
        public Nullable<int> Anomala { get; set; }
        public Nullable<int> dCorrecto { get; set; }
        public Nullable<int> dAnomala { get; set; }
        public Nullable<int> dCantidad { get; set; }
        public Nullable<int> dCritica { get; set; }
        public Nullable<int> cCantidad { get; set; }
        public Nullable<int> cCorrectos { get; set; }
        public Nullable<int> cAnomalas { get; set; }
        public Nullable<int> cCriticas { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> DiaMes { get; set; }
        public Nullable<int> Semana { get; set; }
        public Nullable<int> DiaSemana { get; set; }
        public Nullable<int> DiaAnio { get; set; }
        public string MesName { get; set; }
        public string DayName { get; set; }
    }
}
